env: prod
ossEndpoint: http://oss-cn-hangzhou-internal.aliyuncs.com
server:
  port: 8080
  servlet:
    context-path: /ecms

spring:
  datasource:
    name: prod
    url: jdbc:mysql://rm-bp17nc53804u185nm.mysql.rds.aliyuncs.com:3306/ecms?autoReconnect=true&useSSL=false
    username: ecms_prod_wr
    password: Ecms2019_wr
  redis:
    database: 0
    host: 172.16.150.67
    port: 6379
    password: hadoop@123
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0

activiti:
  database-schema-update:true