env: dev
ossEndpoint: http://oss-cn-hangzhou.aliyuncs.com
server:
  port: 8088
  servlet:
    context-path: /ecms

spring:
  datasource:
    name: dev
    url: jdbc:mysql://47.99.51.34:3306/ecms_dev?autoReconnect=true&useSSL=false&characterEncoding=utf8
    username: ecms
    password: ecms_2018
#    url: jdbc:mysql://localhost:3306/ecms_dev?autoReconnect=true&useSSL=false&characterEncoding=utf8
#    username: root
#    password: root
  redis:
    database: 0
    host: 47.94.236.201
    port: 6379
    password: hadoop@123
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
#logging:
#  level:
#    com.ecms.dal.mapper: debug
activiti:
  database-schema-update:true