CREATE TABLE `seller_customer` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键，客户编号',
  `company_id` int(11) unsigned NOT NULL COMMENT '公司编号',
  `customer_name` varchar(32) DEFAULT NULL COMMENT '名称',
  `tax_number` varchar(64) DEFAULT NULL COMMENT '税号',
  `address_province` varchar(16) DEFAULT NULL COMMENT '省',
  `address_city` varchar(32) DEFAULT NULL COMMENT '市',
  `address_county` varchar(32) DEFAULT NULL COMMENT '区/县',
  `address_detail` varchar(64) DEFAULT NULL COMMENT '门牌号',
  `tax_include` int(11) unsigned NOT NULL COMMENT '是否含税，1是，0不是',
  `contacter_name` varchar(32) DEFAULT NULL COMMENT '联系人姓名',
  `contacter_phone` varchar(32) DEFAULT NULL COMMENT '联系人电话号码',
  `customer_phone` varchar(32) DEFAULT NULL COMMENT '客户电话',
  `pay_type` varchar(32) DEFAULT '' COMMENT '付款方式',
  `pay_rule` varchar(32) DEFAULT '' COMMENT '付款规则',
  `invoice` varchar(32) DEFAULT NULL COMMENT '发票类型',
  `delivery` varchar(32) DEFAULT NULL COMMENT '送货方式',
  `status` int(11) unsigned NOT NULL DEFAULT '1' COMMENT '状态，1合法，0非法',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_companyId` (`company_id`),
  KEY `idx_province` (`address_province`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='销售-客户资料';