CREATE TABLE `warehousing_entry` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `material_id` int(11) NOT NULL COMMENT '物料id',
  `repertory_id` int(11) NOT NULL COMMENT '所在仓库',
  `shelf_position` varchar(128) DEFAULT NULL COMMENT '待入库位',
  `created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` int(1) DEFAULT '1',
  `company_id` int(11) NOT NULL,
  `supplier_id` int(11) DEFAULT NULL COMMENT '来源供应商',
  `qty` float DEFAULT NULL COMMENT '数量',
  `materiel_batch` varchar(128) DEFAULT NULL COMMENT '批次号',
  `purchase_cause` varchar(128) DEFAULT NULL COMMENT '采购原因',
  `origin_of_materiel` varchar(128) DEFAULT NULL COMMENT '物料来源',
  `materiel_stock_from` varchar(45) DEFAULT NULL COMMENT '到货时间',
  `materiel_expiry_date` varchar(128) DEFAULT NULL COMMENT '保质期',
  `materiel_consignee` varchar(45) DEFAULT NULL COMMENT '签收人',
  `estimated_date` varchar(45) DEFAULT NULL,
  `purchase_order_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;