CREATE TABLE `purchase_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL,
  `status` int(11) NOT NULL DEFAULT '1',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `purchase_order_supplier_id` int(11) DEFAULT NULL COMMENT '物料供应商编号',
  `purchase_order_material_id` int(11) NOT NULL COMMENT '物料编号',
  `purchase_order_qty` float DEFAULT NULL COMMENT '订单数量',
  `purchase_order_price` float DEFAULT NULL COMMENT '单价',
  `purchase_order_total` float DEFAULT NULL COMMENT '合计',
  `purchase_order_reason` varchar(128) DEFAULT NULL COMMENT '采购原因',
  `purchase_order_lastest_date` varchar(45) DEFAULT NULL COMMENT '预计到货时间',
  `purchase_order_buyer` varchar(128) DEFAULT NULL COMMENT '采购人',
  `purchase_order_number` varchar(128) DEFAULT NULL COMMENT '采购单号',
  `purchase_order_approval` int(1) DEFAULT NULL COMMENT '审批结果',
  `purchase_order_date` varchar(45) DEFAULT NULL COMMENT '采购下单时间',
  `purchase_order_payment_date` varchar(45) DEFAULT NULL COMMENT '付款时间',
  `purchase_order_arrived` int(1) DEFAULT '0',
  `purchase_order_arrived_date` varchar(45) DEFAULT NULL,
  `purchase_order_repertory_id` int(11) DEFAULT NULL COMMENT '入库仓库',
  `purchase_order_estimated_date` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8;
