CREATE TABLE `seller_order` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键，订单ID',
  `company_id` int(11) unsigned NOT NULL COMMENT '公司编号',
  `contract_id` varchar(64) DEFAULT NULL COMMENT '合同编号',
  `owner` varchar(32) NOT NULL DEFAULT '' COMMENT '制单人',
  `create_date` varchar(16) NOT NULL DEFAULT '' COMMENT '制单日期',
  `customer_id` int(11) unsigned NOT NULL COMMENT '客户编号',
  `customer_name` varchar(32) DEFAULT NULL COMMENT '客户名称',
  `contacter_name` varchar(32) DEFAULT NULL COMMENT '联系人',
  `delivery_address` varchar(64) DEFAULT NULL COMMENT '送货地址',
  `delivery_date` varchar(16) DEFAULT NULL COMMENT '交货日期',
  `tax_include` int(11) unsigned DEFAULT NULL COMMENT '是否含税',
  `product_number` int(11) unsigned DEFAULT NULL COMMENT '产品数量',
  `freight` int(11) unsigned DEFAULT NULL COMMENT '运费',
  `total_money` int(11) unsigned DEFAULT NULL COMMENT '订单总价',
  `pay_type` varchar(32) DEFAULT NULL COMMENT '付款方式',
  `pay_rule` varchar(32) DEFAULT NULL COMMENT '付款时间',
  `invoice` varchar(32) DEFAULT NULL COMMENT '发票类型',
  `delivery` varchar(32) DEFAULT NULL COMMENT '送货方式',
  `progress` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '进度',
  `status` int(11) unsigned NOT NULL DEFAULT '1' COMMENT '状态，1合法，0非法',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_companyId` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='销售-订单';