CREATE TABLE `product_unqualified_report` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `company_id` int(11) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `product_unqualified_report_order_number` varchar(255) DEFAULT NULL,
  `product_unqualified_report_purchase_order` varchar(255) DEFAULT NULL,
  `product_unqualified_report_production_number` varchar(255) DEFAULT NULL,
  `product_unqualified_report_production_item_number` varchar(255) DEFAULT NULL,
  `product_unqualified_report_material_number` varchar(255) DEFAULT NULL,
  `product_unqualified_report_material_name` varchar(255) DEFAULT NULL,
  `product_unqualified_report_origin_material` varchar(255) DEFAULT NULL,
  `product_unqualified_report_parameters` varchar(255) DEFAULT NULL,
  `product_unqualified_report_production_responsible` varchar(255) DEFAULT NULL,
  `product_unqualified_report_production_date` varchar(255) DEFAULT NULL,
  `product_unqualified_report_qty` float DEFAULT NULL,
  `product_unqualified_report_unqualified_qty` float DEFAULT NULL,
  `product_unqualified_report_inspector` varchar(255) DEFAULT NULL,
  `product_unqualified_report_inspect_date` varchar(255) DEFAULT NULL,
  `product_unqualified_report_unqualified_type` varchar(255) DEFAULT NULL,
  `product_unqualified_report_unqualified_desc` varchar(255) DEFAULT NULL,
  `product_unqualified_report_attach` varchar(255) DEFAULT NULL,
  `product_unqualified_report_person_responsible` varchar(255) DEFAULT NULL,
  `product_unqualified_report_depart_responsible` varchar(255) DEFAULT NULL,
  `product_unqualified_report_person_review_responsible` varchar(255) DEFAULT NULL,
  `product_unqualified_report_review_date` varchar(255) DEFAULT NULL,
  `product_unqualified_report_analysis_causes` varchar(255) DEFAULT NULL,
  `product_unqualified_report_analyser` varchar(255) DEFAULT NULL,
  `product_unqualified_report_analysed_date` varchar(255) DEFAULT NULL,
  `product_unqualified_report_disposal_handle_id` int(11) DEFAULT NULL,
  `product_unqualified_report_disposal_causes` varchar(255) DEFAULT NULL,
  `product_unqualified_report_disposal_handler` varchar(255) DEFAULT NULL,
  `product_unqualified_report_disposal_date` varchar(255) DEFAULT NULL,
  `product_unqualified_report_check_log_id` int(11) DEFAULT NULL,
  `product_unqualified_report_editable` int(11) DEFAULT NULL,
  `product_unqualified_report_changed_material_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8