CREATE TABLE `incoming_inspection` (
  `id` bigint(32) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `order_number` varchar(32) DEFAULT NULL COMMENT '采购单号',
  `supplier_name` varchar(32) DEFAULT NULL COMMENT '供应商名称',
  `materiel_number` varchar(32) DEFAULT NULL COMMENT '物料编号',
  `materiel_name` varchar(32) DEFAULT NULL COMMENT '物料名称',
  `raw_material` varchar(32) DEFAULT NULL COMMENT '原材料',
  `parameter1` varchar(32) DEFAULT NULL COMMENT '参数一',
  `parameter2` varchar(32) DEFAULT NULL COMMENT '参数二',
  `parameter3` varchar(32) DEFAULT NULL COMMENT '参数三',
  `parameter4` varchar(32) DEFAULT NULL COMMENT '参数四',
  `parameter5` varchar(32) DEFAULT NULL COMMENT '参数五',
  `total_number` int(11) unsigned DEFAULT NULL COMMENT '总数量',
  `total_unqualified_number` int(11) unsigned DEFAULT NULL COMMENT '不合格数量',
  `production_type` varchar(11) DEFAULT NULL COMMENT '生产类型',
  `product_name` varchar(11) DEFAULT NULL COMMENT '产品名称',
  `production_date` timestamp NULL DEFAULT NULL COMMENT '计划生产日期',
  `materiel_status` int(11) unsigned DEFAULT NULL COMMENT '物料状态：0:备齐，1:缺失',
  `company_id` int(1) unsigned DEFAULT NULL COMMENT '公司编号',
  `order_reason` varchar(64) DEFAULT NULL COMMENT '采购原因',
  `qualified_percent` varchar(255) DEFAULT NULL COMMENT '合格率',
  `total_qualified_number` int(10) unsigned DEFAULT NULL COMMENT '合格数量',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;