CREATE TABLE `production_plan` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `product_id` varchar(255) DEFAULT NULL COMMENT '产品id',
  `product_name` varchar(255) DEFAULT NULL COMMENT '产品名称',
  `product_batch` varchar(255) DEFAULT NULL COMMENT '生产项次',
  `plan_product_date` varchar(10) DEFAULT NULL COMMENT '计划生产日期',
  `latest_product_date` varchar(10) DEFAULT NULL COMMENT '最晚生产日期',
  `materiel_status` int(1) unsigned DEFAULT NULL COMMENT '物料状态',
  `materiel_num` float(11,4) unsigned DEFAULT NULL COMMENT '数量',
  `original_material` varchar(255) DEFAULT NULL COMMENT '原图材料',
  `materiel_unit` varchar(255) DEFAULT NULL COMMENT '单位',
  `created` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '添加时间',
  `updated` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `status` int(1) unsigned DEFAULT '1' COMMENT '状态',
  `company_id` int(11) unsigned DEFAULT NULL COMMENT '公司id',
  `production_number` bigint(11) unsigned zerofill DEFAULT NULL COMMENT '生产单号',
  `primary_id_str` varchar(255) DEFAULT NULL COMMENT '用于判断唯一标识',
  `production_status` int(1) unsigned DEFAULT '1' COMMENT '生产状态1:未完成2：完成',
  `complete_date` varchar(20) DEFAULT NULL COMMENT '生产完成时间',
  `production_type` int(1) unsigned DEFAULT NULL COMMENT '生产类型',
  `unQualified_num` int(11) unsigned DEFAULT NULL COMMENT '不良品数',
  `check_flag` int(1) unsigned DEFAULT '1' COMMENT '检测状态1：待检测，2：已检测',
  `unqualified_qty` int(11) unsigned DEFAULT '0' COMMENT '不合格数',
  `qualified_qty` int(11) unsigned DEFAULT '0' COMMENT '合格数',
  `qualified_percent` varchar(11) DEFAULT NULL COMMENT '合格率',
  `check_order` varchar(20) DEFAULT NULL COMMENT '检测单号',
  `check_date` varchar(20) DEFAULT NULL COMMENT '检测时间',
  `check_person` varchar(20) DEFAULT NULL COMMENT '检测人',
  `product_type` int(1) unsigned DEFAULT NULL COMMENT '产品类型 1：产品，2：物料',
  `upper_mark` varchar(255) DEFAULT NULL COMMENT '上一级标识',
  `materiel_id` int(11) unsigned DEFAULT NULL COMMENT '物料id',
  `materiel_name` varchar(255) DEFAULT NULL COMMENT '物料名称',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=26954 DEFAULT CHARSET=utf8;

